version: "3"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                VARIANT: "6.0"
                NODE_VERSION: "lts/*"
                USER_UID: 1000
                USER_GID: 1000
        volumes:
            - ..:/workspace:cached
        command: sleep infinity