name: release-lib
on:
  push:
    branches:
      - main

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code from the repository
        uses: actions/checkout@v2

      - run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/DavidViolet18/index.json"

      - run: dotnet pack src/SqlBuilder/Dapper.SqlBuilder.csproj --configuration release 

      - run: dotnet nuget push "**/*.nupkg" --source github --skip-duplicate --api-key ${{secrets.DADOU_PTA_PACKAGES}}
      